### ISSUE TITLE
Duplicate Fields in Extended Profile

### ISSUE THREAD

**Issue by garrett-eclipse** [christianwach/bp-xprofile-wp-user-sync#3] opened 2015-02-03 00:36 UTC
Hello,

With WordPress 4.1 and Buddypress 2.1.1 I'm experiencing duplicate Fields in the Admin backend on the Extended Profile tab. The front end edit and register appear to not have the issue, however the front end profile view is also displaying these duplicates.

This may be related to this issue so I've asked for an update for their resolution:
https://wordpress.org/support/topic/double-data

And I've attached screens of the issue:
http://i.imgur.com/ouBzUOV.png
http://i.imgur.com/ggCUeVj.png
http://i.imgur.com/CEALbo7.png

Deactivating and reactivating recreates the issue for me, but at least deactivating gets rid of it.

A nuance of the issue is it seems the Name field which should be removed/hidden reappears into the backend and view pages.

If you need access to my development instance please let me know.
Greatly appreciated.
P.S. Sorry I this is a duplicate of my WP Support Post: https://wordpress.org/support/topic/admin-extended-profile-displaying-duplicate-fields?replies=1#post-6516073

**Comment by garrett-eclipse** [comment] 2015-02-03 01:17
Update - This is resolved by disabling the W3 Total Cache's Object Cache.
Any clue as to why this poses a conflict?
Thanks

**Comment by christianwach** [comment] 2015-02-03 09:48
@garrett-eclipse As per [my comment on wp.org](https://wordpress.org/support/topic/double-data?replies=9#post-6517242) I'll amend the `bp_has_profile` args *before* the main query, which is now possible since BuddyPress 2.1. This may solve the issue.

**Comment by christianwach** [comment] 2015-02-03 14:40
@garrett-eclipse I've started a branch for testing whether the pre-filter approach will work better with object caching:
https://github.com/christianwach/bp-xprofile-wp-user-sync/tree/pre-filter

**Comment by garrett-eclipse** [comment] 2015-02-03 18:00
Thanks @christianwach that's awesome, I cloned the branch and uploaded to my test server with great success. Seems to be working perfectly now with and without Object Caching enabled.
Let me know if there's any other test cases you'd like me to try and I'll play around.
But as far as I can see we're good to merge into the next update.
One thing that I probably won't be able to test for you however is pre-2.1 Buddypress instances.
Cheers

**Comment by christianwach** [comment] 2015-02-03 18:03
Pinging @sbrajesh - would you be able to test this with your unusual registration form locations?

**Comment by sbrajesh** [comment] 2015-02-03 18:39
Hi @christianwach 
the pre filter branch works perfectly for my setup.
Keep up the good work.
Thank you
Brajesh

**Comment by garrett-eclipse** [comment] 2015-02-03 20:21
Hi @christianwach, I'm not sure if this is caused by your plugin but I noticed that the Edit is working fine and has Name split into First and Last but that on the View it's just the combined Name field. See screens below.
![screen shot 2015-02-03 at 12 20 05 pm](https://cloud.githubusercontent.com/assets/8726005/6028531/2f8be790-ab9f-11e4-95c8-c9c71ba264cc.png)
![screen shot 2015-02-03 at 12 20 16 pm](https://cloud.githubusercontent.com/assets/8726005/6028530/2f8a1172-ab9f-11e4-8c40-fabfd8e9ae6f.png)

Let me know if there's anything I can do to troubleshoot this for you.
Thanks

**Comment by christianwach** [comment] 2015-02-03 22:55
@sbrajesh Thanks for checking, much appreciated.

**Comment by christianwach** [comment] 2015-02-03 23:01
@garrett-eclipse That's actually by design, because the plugin was designed to *enforce* full names. I'll add some kind of filter so you can switch this behaviour off if that would be useful. This whole area's part of my roadmap for the plugin, since I'd like to extend its behaviour when used in combination with [CiviCRM WordPress Profile Sync](https://github.com/christianwach/civicrm-wp-profile-sync) to include fields such as "honorific". It'll probably need some kind of admin page to manage the field mappings.

**Comment by garrett-eclipse** [comment] 2015-02-03 23:10
Ah ok sounds good, appreciate the information, sounds like a very useful feature moving forward. Thanks again.

**Comment by christianwach** [comment] 2015-02-04 13:47
@garrett-eclipse I've added a filter so that you can override this plugin's profile view behaviour. So, if you want to have "First Name" and "Last Name" on the profile view screen, use something like the following in a plugin or your theme's 'functions.php' file:

```php
add_filter( 'bp_xprofile_wp_user_sync_exclude_fields', 'my_function_name' );
function my_function_name( $exclude_fields ) {
	return bp_xprofile_fullname_field_id();
}
```

Rename `my_function_name`, obviously! The code is in the 'pre-filter' branch if you want to test it out. If it works for you, I'll push to the WP repo.

**Comment by garrett-eclipse** [comment] 2015-02-06 17:31
Thanks @christianwach, sorry for the delay was pulled into a new project. 
I downloaded the latest from the pre-filter branch and updated the plugin, then placed the following into my functions.php:
```php
function bp_xprofile_wp_user_sync_split_fullname($exclude_fields) {
    return bp_xprofile_fullname_field_id();
}
add_filter('bp_xprofile_wp_user_sync_exclude_fields', 'bp_xprofile_wp_user_sync_split_fullname');
```

But nothing seems to happen, no errors either. And I made sure to clear my caches.

Any thoughts?
Thanks

**Comment by christianwach** [comment] 2015-02-18 12:14
@garrett-eclipse Sorry - I missed this. Did you get the filter working?

**Comment by christianwach** [comment] 2015-02-18 13:37
@garrett-eclipse I've added a new commit that should enable the filter for you if it wasn't working previously. @sbrajesh This may impact your registration form plugin because it is not possible to determine if we are in the loop prior to the query being made. I am checking whether the user ID is empty  instead. The commit works for me in all situations I can find, but I don't have access to your plugin.

**Comment by nightbook** [comment] 2015-02-20 18:22
Thanks @christianwach, you're a rock star.

I was able to test this today and everything is looking in order. The name is properly split into First Name and Last Name now on the Profile View tab (screen below);
![screen shot 2015-02-20 at 10 19 19 am](https://cloud.githubusercontent.com/assets/670280/6306691/5c95dc34-b8ea-11e4-818a-8b13fcc39c0c.png)

So far haven't experienced any issues so if all goes well with @sbrajesh and his testing should be good to merge into the master for an official update release.

Again thank you for your support and assistance.
Enjoy your weekend,
Cheers

**Comment by garrett-eclipse** [comment] 2015-02-20 18:25
*Sorry for the repost accidentally used my personal Github

Thanks @christianwach, you're a rock star.

I was able to test this today and everything is looking in order. The name is properly split into First Name and Last Name now on the Profile View tab (screen below);
![screen shot 2015-02-20 at 10 19 19 am](https://cloud.githubusercontent.com/assets/670280/6306691/5c95dc34-b8ea-11e4-818a-8b13fcc39c0c.png)

So far haven't experienced any issues so if all goes well with @sbrajesh and his testing should be good to merge into the master for an official update release.

Again thank you for your support and assistance.
Enjoy your weekend,
Cheers

**Comment by garrett-eclipse** [comment] 2015-02-20 18:30
BTW, this is the working filter I placed into my functions.php;
```php
function bp_xprofile_wp_user_sync_split_fullname($exclude_fields) {
    return bp_xprofile_fullname_field_id();
}
add_filter('bp_xprofile_wp_user_sync_exclude_fields', 'bp_xprofile_wp_user_sync_split_fullname');
```

**Comment by christianwach** [comment] 2015-02-23 10:32
Merged via ded1a3c93d024517c37119e0a07749cd2fcaad96. Pushing to WP repo now.

**Closed by christianwach** 2015-02-23 10:32 UTC

**Comment by garrett-eclipse** [comment] 2015-02-24 20:15
Thanks again @christianwach greatly appreciated

**Comment by edqu** [comment] 2023-06-22 13:32
You don't need to do any code editing, all you have to do is turn of profile syncing in the buddypress settings options page
